((nil . ((company-clang-arguments . ("-I../include/YAGE/"
				     "-I../../include/YAGE/"
				     "-I../../../include/YAGE/"
                     "-I../include/YAGE/Physics/"
				     "-I../../include/YAGE/Physics/"
				     "-I../../../include/YAGE/Physics/"
                     "-I../include/YAGE/Math/"
				     "-I../../include/YAGE/Math/"
				     "-I../../../include/YAGE/Math/"
				     "-I/usr/include/"
				     "-I/usr/include/SDL2/")) 
	 (company-c-headers-path-user . ("../include/YAGE/"
					 "../../include/YAGE/"
					 "../../../include/YAGE/"
                     "../include/YAGE/Physics/"
					 "../../include/YAGE/Physics/"
					 "../../../include/YAGE/Physics/"
                     "../include/YAGE/Math/"
					 "../../include/YAGE/Math/"
					 "../../../include/YAGE/Math/"
					 "/usr/include/"
					 "/usr/include/SDL2/"))
	 (flycheck-clang-include-path . ("../include/YAGE/"
					 "../../include/YAGE/"
					 "../../../include/YAGE/"
                     "../include/YAGE/Physics/"
					 "../../include/YAGE/Physics/"
					 "../../../include/YAGE/Physics/"
                     "../include/YAGE/Math/"
					 "../../include/YAGE/Math/"
					 "../../../include/YAGE/Math/"
					 "/usr/include/"
					 "/usr/include/SDL2/")))))

