language: cpp
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master
    - develop

notifications:
  email: false

git:
  depth: 3

#############
# Compilers #
#############

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

################
# Dependencies #
################

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libegl1-mesa-dev
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libglm-dev

################
# Build Script #
################

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest
