language: cpp
sudo: required
os: linux
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libegl1-mesa-dev
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libglm-dev

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..
  - make

branches:
  only:
    - master
    - develop

notifications:
  email: false
