language: cpp
dist: trusty

branches:
  only:
    - master
    - develop

notifications:
  email: false

git:
  depth: 1

#############
# Compilers #
#############

matrix:
  include:
    - os: linux
      compiler: gcc

################
# Dependencies #
################

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libegl1-mesa-dev
  - sudo apt-get install -y libgles2-mesa-dev
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y libglm-dev

################
# Build Script #
################

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build
  - cd build
  - cmake -DENABLE_TESTING=1 ..
  - make
  - ctest
  - branch=$(git symbolic-ref HEAD | sed -r -e 's:.*/(.*):\1:')
  - 'if [ "$branch" = "master" ]; then
       ../tools/update_docs
     fi'
