#!/usr/bin/env bash

if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    doxygen ./docs/Doxyfile
    cd html
    git init
    git config user.name "TravisBot"
    git config user.email ""
    git remote add upstream "https://$GH_TOKEN@github.com/ymherklotz/YAGE.git"
    git fetch upstream
    git reset upstream/gh-pages
    touch .
    git add -A .
    git commit -m "Rebuilding documentation"
    git push -q upstream HEAD:gh-pages
    cd ..
fi
