#!/usr/bin/env bash

doxygen ./docs/Doxyfile >/dev/null 2>&1
cd html >/dev/null 2>&1
git init >/dev/null 2>&1
git config user.name "TravisBot" >/dev/null 2>&1
git config user.email "" >/dev/null 2>&1
git remote add upstream "https://$GH_TOKEN@github.com/ymherklotz/YAGE.git" >/dev/null 2>&1
git fetch upstream >/dev/null 2>&1
git reset upstream/gh-pages >/dev/null 2>&1
git add -A >/dev/null 2>&1
git commit -m "Rebuilding documentation" >/dev/null 2>&1
git push -q upstream HEAD:gh-pages >/dev/null 2>&1
